services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - client
    restart: always
    ports:
      - "80:80"
    # Reload nginx configs and certs every 6 hours
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx:/etc/nginx/conf.d
  client:
    restart: always
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOME=/app
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
